### ISSUE TITLE
image's id is not updated when parent page's url change

### ISSUE THREAD

**Issue by Benjamin-Bach** [mullema/k3-image-clip#16]
Hello,
The native image field uses only the relative image's name.
The image-clip field seems to use an absolute id, which does not update when changing the url of a parent page ...

**Comment by mullema** [comment]
Hi Benjamin
I looked into this. The image clip field does the exact same thing as the native files field. It does save the image id, which by design has to include the full slug. If you change the source pages's name, no content file is automatically updated. You can use the slug/id in a query or in your code...how should Kirby know what to update?

There may be unique page id's in Kirby 3.6+ which could solve this problem.
