### ISSUE TITLE
3.8 Compatibility

### ISSUE THREAD

**Issue by mullema** [mullema/k3-image-clip#25]
The model object must use the "Kirby\Filesystem\IsFile" trait in file: ...\Codebase\kirby\src\Filesystem\File.php line: 448

**Comment by afbora** [comment]
Could you share your extending method please?

**Comment by mullema** [comment]
Hi @afbora, not sure what you mean.

That's the extended class.
https://github.com/mullema/k3-image-clip/blob/master/classes/File.php
```php
<?php

namespace mullema;

use Kirby\Cms;

class File extends Cms\File {
```

**Comment by afbora** [comment]
@lukasbestle, `class_uses` only returns traits of the current class. This error occurs because the extended class does not include its traits. Do you have an idea for a more comprehensive solution?

**Comment by lukasbestle** [comment]
@afbora I see three possible solutions:

- We loop through `class_parents()` and check each parent class if it uses the trait.
- We create an interface and check for that instead of the trait. Unfortunately it is not possible to implement an interface directly in a trait. So we would need to implement the interface in our classes (not pretty).
- We switch to a duck test for the existence of the `root` and `url` methods.

**Comment by distantnative** [comment]
@lukasbestle @afbora I'd go for the latter - interface would be clean but then again all plugins would need to implement the interface and first will have breaking change errors. I think checking for those two methods would be sufficient and the least painful way right now.

**Comment by lukasbestle** [comment]
I have created an issue in the Kirby repo: https://github.com/getkirby/kirby/issues/4748
This issue can IMO be closed as it's not an issue in the plugin code but an regression in Kirby.

**Comment by mullema** [comment]
Thx
